//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trivago3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL_BOOKING
    {
        public string HOTELID { get; set; }
        public string CUSTOMERID { get; set; }
        public Nullable<System.DateTime> CHECK_IN { get; set; }
        public Nullable<System.DateTime> CHECK_OUT { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual HOTEL HOTEL { get; set; }
    }
}
