//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trivago3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOTEL()
        {
            this.HOTEL_BOOKING = new HashSet<HOTEL_BOOKING>();
        }
    
        public string HOTELID { get; set; }
        public string NAME { get; set; }
        public string CONTACT { get; set; }
        public string LOCATION { get; set; }
        public string DESCRIPTION { get; set; }
        public string AGENTID { get; set; }
    
        public virtual AGENT AGENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOTEL_BOOKING> HOTEL_BOOKING { get; set; }
    }
}
