//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trivago3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACKAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACKAGE()
        {
            this.PACKAGE_BOOKING = new HashSet<PACKAGE_BOOKING>();
        }
    
        public string PACKAGEID { get; set; }
        public string PRICE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ACTIVITIES { get; set; }
        public string NO_OF_DAYS { get; set; }
        public string PLACES { get; set; }
        public string AGENTID { get; set; }
    
        public virtual AGENT AGENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKAGE_BOOKING> PACKAGE_BOOKING { get; set; }
    }
}
