//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trivago3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TRIVAGO2Entities : DbContext
    {
        public TRIVAGO2Entities()
            : base("name=TRIVAGO2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENT> AGENTs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<HOTEL> HOTELs { get; set; }
        public virtual DbSet<HOTEL_BOOKING> HOTEL_BOOKING { get; set; }
        public virtual DbSet<PACKAGE_BOOKING> PACKAGE_BOOKING { get; set; }
        public virtual DbSet<PACKAGE> PACKAGES { get; set; }
    }
}
